FROM maven:3.9.5-amazoncorretto-11

RUN yum install -y curl jq tr

WORKDIR /var/src/app

COPY ./src ./src
COPY ./pom.xml ./pom.xml

RUN mkdir results || true
RUN chmod 777 results
RUN mkdir downloads || true

RUN echo "Build successful!"